POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="jpg.jpg"
Content-Type: image/jpeg

< ./filesToUpload/jpg.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

nazwa_albumu
------FormBoundary1234

### GET - pobierz wszystkie dane
GET http://localhost:3000/api/photos HTTP/1.1

### GET - pobierz jednego fotosa
GET http://localhost:3000/api/photos/1653301525107 HTTP/1.1

### PATCH - zmień jednego fotosa
PATCH  http://localhost:3000/api/photos/1653300746863 HTTP/1.1

### DELETE - usuń jednego fotosa
DELETE  http://localhost:3000/api/photos/1653045462066 HTTP/1.1